name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Continue with other builds even if one fails
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: cforge
            asset_name: cforge-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: cforge.exe
            asset_name: cforge-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: cforge
            asset_name: cforge-macos-amd64

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
          
      - name: Prepare artifact
        shell: bash
        run: |
          mkdir -p release-artifacts
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} release-artifacts/${{ matrix.asset_name }}
          else
            cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} release-artifacts/${{ matrix.asset_name }}
          fi
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: ${{ matrix.asset_name }}
          path: release-artifacts/${{ matrix.asset_name }}
          
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          path: artifacts
        
      - name: List artifacts
        run: ls -R artifacts
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/cforge-linux-amd64/cforge-linux-amd64
            artifacts/cforge-windows-amd64.exe/cforge-windows-amd64.exe
            artifacts/cforge-macos-amd64/cforge-macos-amd64
          generate_release_notes: true
