name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: cbuild-tool
            asset_name: cbuild-tool-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: cbuild-tool.exe
            asset_name: cbuild-tool-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: cbuild-tool
            asset_name: cbuild-tool-macos-amd64

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.target }}
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
          
  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            cbuild-tool-linux-amd64/cbuild-tool
            cbuild-tool-windows-amd64.exe/cbuild-tool.exe
            cbuild-tool-macos-amd64/cbuild-tool